### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Saurabh254** [Bearski11/Custom-Discord-Rich-Presence#1]
Hey Buddy, 
I tried using your repository to get my bot rich presence. But me landed with an unknown error. 
I'm using Termux App. 

`
>>> from pypresence import Presence
>>> import time
>>> client_id = "888464683584094208"
>>> RPC = Presence(client_id)
>>> RPC.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pypresence/baseclient.py", line 128, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/streams.py", line 111, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/unix_events.py", line 244, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/data/data/com.termux/files/usr/lib/python3.9/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
>>>
`
Help me with This..

**Comment by LopeKinz** [comment]
Its meant for windows… not for android

**Comment by Bearski11** [comment]
It's meant for a desktop operating system like BSD, Linux, and Windows. Not Android, Sorry.
